# Generated by Django 4.0.4 on 2022-06-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_size', models.CharField(blank=True, max_length=64)),
                ('product_color', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_Alert_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alert_config')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField()),
                ('type_sent', models.CharField(blank=True, max_length=64)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alert_config')),
            ],
        ),
        migrations.AddField(
            model_name='alert_config',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alert_status'),
        ),
        migrations.AddField(
            model_name='alert_config',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
