# Generated by Django 4.0.4 on 2022-06-14 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lulu_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_sent', models.DateTimeField()),
                ('sent_method', models.CharField(default='email', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=20)),
                ('target_price', models.IntegerField(blank=True)),
                ('date_set', models.DateField()),
                ('alert_method', models.CharField(default='email', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True)),
                ('currency', models.CharField(max_length=6)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alerts_history',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='user_alert_map',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='user_alert_map',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert_Config',
        ),
        migrations.DeleteModel(
            name='Alerts_History',
        ),
        migrations.DeleteModel(
            name='User_Alert_Map',
        ),
        migrations.AddField(
            model_name='alerts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.products'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alert_status'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert_history',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alerts'),
        ),
    ]
