# Generated by Django 4.0.4 on 2022-06-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_alerts', '0003_remove_alerts_status_alerts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='status',
        ),
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alert_status'),
            preserve_default=False,
        ),
    ]
