# Generated by Django 4.0.4 on 2022-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_alerts', '0004_remove_alerts_status_alerts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
