# Generated by Django 4.0.4 on 2022-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_alerts', '0005_products_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_method', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', error_messages={'required': 'Text coming soon ;)'}, max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='alerts',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
