# Generated by Django 4.0.4 on 2022-06-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_alerts', '0006_test_form_alter_alerts_target_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif_Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notif_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sent_time', models.DateTimeField(blank=True)),
                ('complete_time', models.DateTimeField(blank=True)),
                ('type', models.CharField(default='email', max_length=20)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.alerts')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.notif_origin')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.notif_status')),
            ],
        ),
        migrations.RemoveField(
            model_name='alert_history',
            name='alert',
        ),
        migrations.DeleteModel(
            name='Test_form',
        ),
        migrations.DeleteModel(
            name='Alert_History',
        ),
    ]
