# Generated by Django 4.0.4 on 2022-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lulu_alerts', '0007_notif_origin_notif_status_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='courier_response_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lulu_alerts.notif_origin'),
        ),
    ]
